pipeline {
    agent any

    parameters {
        choice(name: 'terraformAction', choices: ['apply', 'destroy'], description: 'Choose your terraform action')
    }

    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION    = 'us-west-2'
    }

    stages {

        stage('Checkout') {
            steps {
                dir('terraform') {
                    git url: 'https://github.com/Prajwal8651/project-chatbot.git',
                        branch: 'Iac-devenv'
                }
            }
        }

        stage('Plan') {
            steps {
                dir('terraform/eks') {
                    sh 'terraform init'
                    sh 'terraform plan -out=tfplan'
                    sh 'terraform show -no-color tfplan > tfplan.txt'
                }
            }
        }

        stage('Approval') {
            when {
                expression { params.terraformAction == 'apply' }
            }
            steps {
                script {
                    def plan = readFile 'terraform/eks/tfplan.txt'
                    input message: 'Do you want to proceed with Terraform apply?',
                          parameters: [
                              text(name: 'Plan', description: 'Review plan', defaultValue: plan)
                          ]
                }
            }
        }

        stage('Apply or Destroy') {
            steps {
                dir('terraform/eks') {
                    script {
                        if (params.terraformAction == 'apply') {
                            sh 'terraform apply -input=false tfplan'
                        } else {
                            sh 'terraform destroy -auto-approve'
                        }
                    }
                }
            }
        }
    }
}